// <auto-generated />
using AurPackger.Web.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AurPackger.Web.Migrations
{
    [DbContext(typeof(PackageDbContext))]
    [Migration("20230109002630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("AurPackger.Web.Entites.AurPackageModel", b =>
                {
                    b.Property<string>("PackageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalRepoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PackageName");

                    b.ToTable("AurPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
