// <auto-generated />

using AurPackager.Web.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AurPackager.Web.Migrations
{
    [DbContext(typeof(PackageDbContext))]
    partial class PackageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("AurPackager.Web.Entites.AurPackageModel", b =>
                {
                    b.Property<string>("PackageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalRepoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PackageName");

                    b.ToTable("AurPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
